data_path : 'H:/广州市'
shp_name: 'road.shp'
right_shp_name : 'road_right.shp'
ponint_shp_name : 'point_intersection.shp'
img_name: 'raster.tif'
point_num: 1000
out_path: 'H:/result/shanghai100'

road_verify :
  root_dir : './'
  images_pack : 'road_images'
  output_name : 'result'

frcnn:
  model_path: 'model_data/road_voc_weights_resnet.pth'
  classes_path: 'model_data/road_voc_classes.txt'
  confidence: 0.9
  iou: 0.3
  backbone: 'resnet50'
  cuda: True
